import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.scss";
import Link from "next/link";
import Image from 'next/image'

import { Button } from "../components/Widgets";

import competitorImg from '../img/competitor.png';
import endImg from '../img/end.png';
import gradingImg from '../img/grading.png';
import testsImg from '../img/tests.png';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>AutoComp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isAuth={false}>
        <section className={styles.topSection}>
          <div className={styles.topFirstLine}> Online Math Competitions</div>
          <div className={styles.topSecondLine}> Simplified</div>
          <div className={styles.topBody}>
            The platform to reliably run your entire tournament without the
            hassle, from registration to awards.
          </div>
          <div className={styles.topButtonGroup}>
            <Link href="https://forms.gle/EttbSTTrY7NtGnso7">
              <a>
                <Button color="primary">
                  <div className={styles.buttonText}>
                    Join Waitlist Today
                  </div>
                </Button>
              </a>
            </Link>
          </div>
        </section>
        <section className={styles.featureOdd} id="features">
          <div className={styles.featureText}>
            <div className={styles.featureSupertitle}>
              Make your own AMC/AIME
            </div>
            <div className={styles.featureTitle}>Powerful Exams</div>
            <div className={styles.featureBody}>
              Create professional-grade exams with our easy-to-use editor,
              complete with LaTeX, figures, and more!
            </div>
          </div>
          <div className={styles.featureImage}>
            <Image src={testsImg}/>
          </div>
        </section>
        <section className={styles.featureEven}>
          <div className={styles.featureImage}>
            <Image src={gradingImg}/>
          </div>
          <div className={styles.featureText}>
            <div className={styles.featureSupertitle}>Spreadsheets begone</div>
            <div className={styles.featureTitle}>Automated Scoring</div>
            <div className={styles.featureBody}>
              Keep your competition running slowly with our automatic grading
              for multiple choice and numerical questions.
            </div>
          </div>
        </section>
        <section className={styles.featureOdd}>
          <div className={styles.featureText}>
            <div className={styles.featureSupertitle}>
              Everything in one place
            </div>
            <div className={styles.featureTitle}>End-to-End Workflow</div>
            <div className={styles.featureBody}>
              Manage all aspects of your tournament, from registration to
              proctoring to scoring, all in one app.
            </div>
          </div>
          <div className={styles.featureImage}>
            <Image src={endImg}/>
          </div>
        </section>
        <section className={styles.featureEven}>
          <div className={styles.featureImage}>
            <Image src={competitorImg}/>
          </div>
          <div className={styles.featureText}>
            <div className={styles.featureSupertitle}>
              Non-Invasive Test-Taking
            </div>
            <div className={styles.featureTitle}>Competitor Experience</div>
            <div className={styles.featureBody}>
              Keep your competitors happy with an easy-to-use interface, simple
              registration, and fast turnaround times.
            </div>
          </div>
        </section>
        <section id="contact">
          <p>
            
          </p>
        </section>
      </Layout>
    </>
  );
};

export default Home;
